version: '3'

services:
  web:
    image: sysbind/thebuggenie:latest
    build: .
    ports:
    - "8000:80"    

  database:
    image: postgres:alpine
    ports:
    - "5432:5432"    
    environment:
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: tbg
